// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDdz6k6hTPTnM5CapfHDaea034IPkzKDQ',
    appId: '1:622328736158:web:8375a28c616dd254c40e8f',
    messagingSenderId: '622328736158',
    projectId: 'sunsync-322b8',
    authDomain: 'sunsync-322b8.firebaseapp.com',
    storageBucket: 'sunsync-322b8.firebasestorage.app',
    measurementId: 'G-V496JRH5PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcNmTN4Vbv3J2GVqyN_hZ6xf_o1KSVsfA',
    appId: '1:622328736158:android:62086d0c666b5e9dc40e8f',
    messagingSenderId: '622328736158',
    projectId: 'sunsync-322b8',
    storageBucket: 'sunsync-322b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOU6Ui7q6iuXTwYbgEDa18At2rXqf4Ms',
    appId: '1:622328736158:ios:75696e957c3ab813c40e8f',
    messagingSenderId: '622328736158',
    projectId: 'sunsync-322b8',
    storageBucket: 'sunsync-322b8.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcOU6Ui7q6iuXTwYbgEDa18At2rXqf4Ms',
    appId: '1:622328736158:ios:75696e957c3ab813c40e8f',
    messagingSenderId: '622328736158',
    projectId: 'sunsync-322b8',
    storageBucket: 'sunsync-322b8.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDdz6k6hTPTnM5CapfHDaea034IPkzKDQ',
    appId: '1:622328736158:web:a56798dc32eb9fefc40e8f',
    messagingSenderId: '622328736158',
    projectId: 'sunsync-322b8',
    authDomain: 'sunsync-322b8.firebaseapp.com',
    storageBucket: 'sunsync-322b8.firebasestorage.app',
    measurementId: 'G-PT4XV31Y20',
  );
}
