name: Flutter 构建

on:
  push:
    branches: [ main ]
    paths:
      - 'SunSync_app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'SunSync_app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SunSync_app

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置 Java 环境
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: 设置 Flutter 环境
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.2'
        channel: 'stable'
    
    - name: 获取依赖
      run: flutter pub get
    
    # 如果你在 GitHub Secrets 中存储了 Firebase 配置
    - name: 创建 Firebase 配置文件
      run: |
        if [ -n "$GOOGLE_SERVICES_JSON" ]; then
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > android/app/google-services.json
          echo "Firebase 配置文件已创建"
        else
          echo "警告: Firebase 配置未提供"
        fi
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    
    - name: 显示 Flutter 版本
      run: flutter --version
    
    - name: 分析代码
      run: flutter analyze || true
    
    - name: 构建 APK
      run: flutter build apk --release
    
    - name: 重命名 APK 文件
      run: |
        mkdir -p build-outputs
        cp build/app/outputs/flutter-apk/app-release.apk build-outputs/SunSync-$(date +'%Y%m%d')-${{ github.run_number }}.apk
    
    - name: 上传 APK
      uses: actions/upload-artifact@v3
      with:
        name: SunSync-release
        path: SunSync_app/build-outputs/*.apk
        retention-days: 7
