name: Flutter Build

on:
  push:
    branches: [ main ]
    paths:
      - 'SunSync_app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'SunSync_app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SunSync_app

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.2'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: SunSync-release
        path: SunSync_app/build/app/outputs/flutter-apk/app-release.apk
